// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: tbd/service/v1/project_file.proto

package servicev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProjectFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Models  []*ProjectFile_Model  `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	Sources []*ProjectFile_Source `protobuf:"bytes,2,rep,name=sources,proto3" json:"sources,omitempty"`
}

func (x *ProjectFile) Reset() {
	*x = ProjectFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tbd_service_v1_project_file_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectFile) ProtoMessage() {}

func (x *ProjectFile) ProtoReflect() protoreflect.Message {
	mi := &file_tbd_service_v1_project_file_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectFile.ProtoReflect.Descriptor instead.
func (*ProjectFile) Descriptor() ([]byte, []int) {
	return file_tbd_service_v1_project_file_proto_rawDescGZIP(), []int{0}
}

func (x *ProjectFile) GetModels() []*ProjectFile_Model {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *ProjectFile) GetSources() []*ProjectFile_Source {
	if x != nil {
		return x.Sources
	}
	return nil
}

type ProjectFile_Column struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string                           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string                           `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Tests       []*ProjectFile_Column_ColumnTest `protobuf:"bytes,3,rep,name=tests,proto3" json:"tests,omitempty"`
}

func (x *ProjectFile_Column) Reset() {
	*x = ProjectFile_Column{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tbd_service_v1_project_file_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectFile_Column) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectFile_Column) ProtoMessage() {}

func (x *ProjectFile_Column) ProtoReflect() protoreflect.Message {
	mi := &file_tbd_service_v1_project_file_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectFile_Column.ProtoReflect.Descriptor instead.
func (*ProjectFile_Column) Descriptor() ([]byte, []int) {
	return file_tbd_service_v1_project_file_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ProjectFile_Column) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectFile_Column) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProjectFile_Column) GetTests() []*ProjectFile_Column_ColumnTest {
	if x != nil {
		return x.Tests
	}
	return nil
}

type ProjectFile_Model struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string                `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Columns     []*ProjectFile_Column `protobuf:"bytes,3,rep,name=columns,proto3" json:"columns,omitempty"`
}

func (x *ProjectFile_Model) Reset() {
	*x = ProjectFile_Model{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tbd_service_v1_project_file_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectFile_Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectFile_Model) ProtoMessage() {}

func (x *ProjectFile_Model) ProtoReflect() protoreflect.Message {
	mi := &file_tbd_service_v1_project_file_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectFile_Model.ProtoReflect.Descriptor instead.
func (*ProjectFile_Model) Descriptor() ([]byte, []int) {
	return file_tbd_service_v1_project_file_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ProjectFile_Model) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectFile_Model) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProjectFile_Model) GetColumns() []*ProjectFile_Column {
	if x != nil {
		return x.Columns
	}
	return nil
}

type ProjectFile_Source struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// The full path of the source table in the database. This is used to reference the table itself. For example:
	// - 'public.users' for where the schema is 'public' and the table is 'users'
	// - 'project_id_123.dataset_id_123.table_id_123' for a BigQuery table
	Path    string                `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Columns []*ProjectFile_Column `protobuf:"bytes,4,rep,name=columns,proto3" json:"columns,omitempty"`
}

func (x *ProjectFile_Source) Reset() {
	*x = ProjectFile_Source{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tbd_service_v1_project_file_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectFile_Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectFile_Source) ProtoMessage() {}

func (x *ProjectFile_Source) ProtoReflect() protoreflect.Message {
	mi := &file_tbd_service_v1_project_file_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectFile_Source.ProtoReflect.Descriptor instead.
func (*ProjectFile_Source) Descriptor() ([]byte, []int) {
	return file_tbd_service_v1_project_file_proto_rawDescGZIP(), []int{0, 2}
}

func (x *ProjectFile_Source) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectFile_Source) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProjectFile_Source) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ProjectFile_Source) GetColumns() []*ProjectFile_Column {
	if x != nil {
		return x.Columns
	}
	return nil
}

// Standard types are:
// - not_null
// - unique
// - 'relationship' which takes into data (model and field)
type ProjectFile_Column_ColumnTest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string            `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Info map[string]string `protobuf:"bytes,2,rep,name=info,proto3" json:"info,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ProjectFile_Column_ColumnTest) Reset() {
	*x = ProjectFile_Column_ColumnTest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tbd_service_v1_project_file_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectFile_Column_ColumnTest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectFile_Column_ColumnTest) ProtoMessage() {}

func (x *ProjectFile_Column_ColumnTest) ProtoReflect() protoreflect.Message {
	mi := &file_tbd_service_v1_project_file_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectFile_Column_ColumnTest.ProtoReflect.Descriptor instead.
func (*ProjectFile_Column_ColumnTest) Descriptor() ([]byte, []int) {
	return file_tbd_service_v1_project_file_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *ProjectFile_Column_ColumnTest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProjectFile_Column_ColumnTest) GetInfo() map[string]string {
	if x != nil {
		return x.Info
	}
	return nil
}

var File_tbd_service_v1_project_file_proto protoreflect.FileDescriptor

var file_tbd_service_v1_project_file_proto_rawDesc = []byte{
	0x0a, 0x21, 0x74, 0x62, 0x64, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31,
	0x2f, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x74, 0x62, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x76, 0x31, 0x22, 0xc5, 0x05, 0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x46,
	0x69, 0x6c, 0x65, 0x12, 0x39, 0x0a, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x74, 0x62, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x46, 0x69, 0x6c, 0x65,
	0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x12, 0x3c,
	0x0a, 0x07, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x22, 0x2e, 0x74, 0x62, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x2e, 0x53, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x52, 0x07, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x1a, 0xac, 0x02, 0x0a,
	0x06, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x43, 0x0a,
	0x05, 0x74, 0x65, 0x73, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x74,
	0x62, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x2e, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e,
	0x2e, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x54, 0x65, 0x73, 0x74, 0x52, 0x05, 0x74, 0x65, 0x73,
	0x74, 0x73, 0x1a, 0xa6, 0x01, 0x0a, 0x0a, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x54, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x4b, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x74, 0x62, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x46, 0x69, 0x6c, 0x65,
	0x2e, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x2e, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x54, 0x65,
	0x73, 0x74, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x69, 0x6e,
	0x66, 0x6f, 0x1a, 0x37, 0x0a, 0x09, 0x49, 0x6e, 0x66, 0x6f, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x7b, 0x0a, 0x05, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3c, 0x0a, 0x07, 0x63, 0x6f,
	0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x74, 0x62,
	0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x2e, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x52,
	0x07, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x1a, 0x90, 0x01, 0x0a, 0x06, 0x53, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x3c, 0x0a,
	0x07, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22,
	0x2e, 0x74, 0x62, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x2e, 0x43, 0x6f, 0x6c, 0x75,
	0x6d, 0x6e, 0x52, 0x07, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x42, 0x42, 0x50, 0x01, 0x5a,
	0x3e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x65, 0x6e, 0x66,
	0x64, 0x6b, 0x69, 0x6e, 0x67, 0x2f, 0x74, 0x62, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x67, 0x65, 0x6e, 0x2f, 0x67, 0x6f, 0x2f, 0x74, 0x62, 0x64, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tbd_service_v1_project_file_proto_rawDescOnce sync.Once
	file_tbd_service_v1_project_file_proto_rawDescData = file_tbd_service_v1_project_file_proto_rawDesc
)

func file_tbd_service_v1_project_file_proto_rawDescGZIP() []byte {
	file_tbd_service_v1_project_file_proto_rawDescOnce.Do(func() {
		file_tbd_service_v1_project_file_proto_rawDescData = protoimpl.X.CompressGZIP(file_tbd_service_v1_project_file_proto_rawDescData)
	})
	return file_tbd_service_v1_project_file_proto_rawDescData
}

var file_tbd_service_v1_project_file_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_tbd_service_v1_project_file_proto_goTypes = []interface{}{
	(*ProjectFile)(nil),                   // 0: tbd.service.v1.ProjectFile
	(*ProjectFile_Column)(nil),            // 1: tbd.service.v1.ProjectFile.Column
	(*ProjectFile_Model)(nil),             // 2: tbd.service.v1.ProjectFile.Model
	(*ProjectFile_Source)(nil),            // 3: tbd.service.v1.ProjectFile.Source
	(*ProjectFile_Column_ColumnTest)(nil), // 4: tbd.service.v1.ProjectFile.Column.ColumnTest
	nil,                                   // 5: tbd.service.v1.ProjectFile.Column.ColumnTest.InfoEntry
}
var file_tbd_service_v1_project_file_proto_depIdxs = []int32{
	2, // 0: tbd.service.v1.ProjectFile.models:type_name -> tbd.service.v1.ProjectFile.Model
	3, // 1: tbd.service.v1.ProjectFile.sources:type_name -> tbd.service.v1.ProjectFile.Source
	4, // 2: tbd.service.v1.ProjectFile.Column.tests:type_name -> tbd.service.v1.ProjectFile.Column.ColumnTest
	1, // 3: tbd.service.v1.ProjectFile.Model.columns:type_name -> tbd.service.v1.ProjectFile.Column
	1, // 4: tbd.service.v1.ProjectFile.Source.columns:type_name -> tbd.service.v1.ProjectFile.Column
	5, // 5: tbd.service.v1.ProjectFile.Column.ColumnTest.info:type_name -> tbd.service.v1.ProjectFile.Column.ColumnTest.InfoEntry
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_tbd_service_v1_project_file_proto_init() }
func file_tbd_service_v1_project_file_proto_init() {
	if File_tbd_service_v1_project_file_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tbd_service_v1_project_file_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tbd_service_v1_project_file_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectFile_Column); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tbd_service_v1_project_file_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectFile_Model); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tbd_service_v1_project_file_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectFile_Source); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tbd_service_v1_project_file_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectFile_Column_ColumnTest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tbd_service_v1_project_file_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tbd_service_v1_project_file_proto_goTypes,
		DependencyIndexes: file_tbd_service_v1_project_file_proto_depIdxs,
		MessageInfos:      file_tbd_service_v1_project_file_proto_msgTypes,
	}.Build()
	File_tbd_service_v1_project_file_proto = out.File
	file_tbd_service_v1_project_file_proto_rawDesc = nil
	file_tbd_service_v1_project_file_proto_goTypes = nil
	file_tbd_service_v1_project_file_proto_depIdxs = nil
}
