// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: tbd/service/v1/wasm_rpc_test_map.proto

package servicev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WasmRpcSetOfModelsIncludingSeeds_WasmRpcSetOfModelsIncludingSeedsEntry_WasmRpcSetOfModelsIncludingSeedsEntryType int32

const (
	WasmRpcSetOfModelsIncludingSeeds_WasmRpcSetOfModelsIncludingSeedsEntry_WASM_RPC_SET_OF_MODELS_INCLUDING_SEEDS_ENTRY_TYPE_UNSPECIFIED WasmRpcSetOfModelsIncludingSeeds_WasmRpcSetOfModelsIncludingSeedsEntry_WasmRpcSetOfModelsIncludingSeedsEntryType = 0
	WasmRpcSetOfModelsIncludingSeeds_WasmRpcSetOfModelsIncludingSeedsEntry_WASM_RPC_SET_OF_MODELS_INCLUDING_SEEDS_ENTRY_TYPE_MODEL       WasmRpcSetOfModelsIncludingSeeds_WasmRpcSetOfModelsIncludingSeedsEntry_WasmRpcSetOfModelsIncludingSeedsEntryType = 1
	WasmRpcSetOfModelsIncludingSeeds_WasmRpcSetOfModelsIncludingSeedsEntry_WASM_RPC_SET_OF_MODELS_INCLUDING_SEEDS_ENTRY_TYPE_SEED        WasmRpcSetOfModelsIncludingSeeds_WasmRpcSetOfModelsIncludingSeedsEntry_WasmRpcSetOfModelsIncludingSeedsEntryType = 2
)

// Enum value maps for WasmRpcSetOfModelsIncludingSeeds_WasmRpcSetOfModelsIncludingSeedsEntry_WasmRpcSetOfModelsIncludingSeedsEntryType.
var (
	WasmRpcSetOfModelsIncludingSeeds_WasmRpcSetOfModelsIncludingSeedsEntry_WasmRpcSetOfModelsIncludingSeedsEntryType_name = map[int32]string{
		0: "WASM_RPC_SET_OF_MODELS_INCLUDING_SEEDS_ENTRY_TYPE_UNSPECIFIED",
		1: "WASM_RPC_SET_OF_MODELS_INCLUDING_SEEDS_ENTRY_TYPE_MODEL",
		2: "WASM_RPC_SET_OF_MODELS_INCLUDING_SEEDS_ENTRY_TYPE_SEED",
	}
	WasmRpcSetOfModelsIncludingSeeds_WasmRpcSetOfModelsIncludingSeedsEntry_WasmRpcSetOfModelsIncludingSeedsEntryType_value = map[string]int32{
		"WASM_RPC_SET_OF_MODELS_INCLUDING_SEEDS_ENTRY_TYPE_UNSPECIFIED": 0,
		"WASM_RPC_SET_OF_MODELS_INCLUDING_SEEDS_ENTRY_TYPE_MODEL":       1,
		"WASM_RPC_SET_OF_MODELS_INCLUDING_SEEDS_ENTRY_TYPE_SEED":        2,
	}
)

func (x WasmRpcSetOfModelsIncludingSeeds_WasmRpcSetOfModelsIncludingSeedsEntry_WasmRpcSetOfModelsIncludingSeedsEntryType) Enum() *WasmRpcSetOfModelsIncludingSeeds_WasmRpcSetOfModelsIncludingSeedsEntry_WasmRpcSetOfModelsIncludingSeedsEntryType {
	p := new(WasmRpcSetOfModelsIncludingSeeds_WasmRpcSetOfModelsIncludingSeedsEntry_WasmRpcSetOfModelsIncludingSeedsEntryType)
	*p = x
	return p
}

func (x WasmRpcSetOfModelsIncludingSeeds_WasmRpcSetOfModelsIncludingSeedsEntry_WasmRpcSetOfModelsIncludingSeedsEntryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WasmRpcSetOfModelsIncludingSeeds_WasmRpcSetOfModelsIncludingSeedsEntry_WasmRpcSetOfModelsIncludingSeedsEntryType) Descriptor() protoreflect.EnumDescriptor {
	return file_tbd_service_v1_wasm_rpc_test_map_proto_enumTypes[0].Descriptor()
}

func (WasmRpcSetOfModelsIncludingSeeds_WasmRpcSetOfModelsIncludingSeedsEntry_WasmRpcSetOfModelsIncludingSeedsEntryType) Type() protoreflect.EnumType {
	return &file_tbd_service_v1_wasm_rpc_test_map_proto_enumTypes[0]
}

func (x WasmRpcSetOfModelsIncludingSeeds_WasmRpcSetOfModelsIncludingSeedsEntry_WasmRpcSetOfModelsIncludingSeedsEntryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WasmRpcSetOfModelsIncludingSeeds_WasmRpcSetOfModelsIncludingSeedsEntry_WasmRpcSetOfModelsIncludingSeedsEntryType.Descriptor instead.
func (WasmRpcSetOfModelsIncludingSeeds_WasmRpcSetOfModelsIncludingSeedsEntry_WasmRpcSetOfModelsIncludingSeedsEntryType) EnumDescriptor() ([]byte, []int) {
	return file_tbd_service_v1_wasm_rpc_test_map_proto_rawDescGZIP(), []int{1, 0, 0}
}

type WasmRpcTestMap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tests map[string]string `protobuf:"bytes,1,rep,name=tests,proto3" json:"tests,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *WasmRpcTestMap) Reset() {
	*x = WasmRpcTestMap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tbd_service_v1_wasm_rpc_test_map_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WasmRpcTestMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WasmRpcTestMap) ProtoMessage() {}

func (x *WasmRpcTestMap) ProtoReflect() protoreflect.Message {
	mi := &file_tbd_service_v1_wasm_rpc_test_map_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WasmRpcTestMap.ProtoReflect.Descriptor instead.
func (*WasmRpcTestMap) Descriptor() ([]byte, []int) {
	return file_tbd_service_v1_wasm_rpc_test_map_proto_rawDescGZIP(), []int{0}
}

func (x *WasmRpcTestMap) GetTests() map[string]string {
	if x != nil {
		return x.Tests
	}
	return nil
}

type WasmRpcSetOfModelsIncludingSeeds struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Models []*WasmRpcSetOfModelsIncludingSeeds_WasmRpcSetOfModelsIncludingSeedsEntry `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
}

func (x *WasmRpcSetOfModelsIncludingSeeds) Reset() {
	*x = WasmRpcSetOfModelsIncludingSeeds{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tbd_service_v1_wasm_rpc_test_map_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WasmRpcSetOfModelsIncludingSeeds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WasmRpcSetOfModelsIncludingSeeds) ProtoMessage() {}

func (x *WasmRpcSetOfModelsIncludingSeeds) ProtoReflect() protoreflect.Message {
	mi := &file_tbd_service_v1_wasm_rpc_test_map_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WasmRpcSetOfModelsIncludingSeeds.ProtoReflect.Descriptor instead.
func (*WasmRpcSetOfModelsIncludingSeeds) Descriptor() ([]byte, []int) {
	return file_tbd_service_v1_wasm_rpc_test_map_proto_rawDescGZIP(), []int{1}
}

func (x *WasmRpcSetOfModelsIncludingSeeds) GetModels() []*WasmRpcSetOfModelsIncludingSeeds_WasmRpcSetOfModelsIncludingSeedsEntry {
	if x != nil {
		return x.Models
	}
	return nil
}

type WasmRpcSetOfModelsIncludingSeeds_WasmRpcSetOfModelsIncludingSeedsEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModelName   string                                                                                                           `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Description string                                                                                                           `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ModelOrSeed WasmRpcSetOfModelsIncludingSeeds_WasmRpcSetOfModelsIncludingSeedsEntry_WasmRpcSetOfModelsIncludingSeedsEntryType `protobuf:"varint,3,opt,name=model_or_seed,json=modelOrSeed,proto3,enum=tbd.service.v1.WasmRpcSetOfModelsIncludingSeeds_WasmRpcSetOfModelsIncludingSeedsEntry_WasmRpcSetOfModelsIncludingSeedsEntryType" json:"model_or_seed,omitempty"`
	FilePath    string                                                                                                           `protobuf:"bytes,4,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
}

func (x *WasmRpcSetOfModelsIncludingSeeds_WasmRpcSetOfModelsIncludingSeedsEntry) Reset() {
	*x = WasmRpcSetOfModelsIncludingSeeds_WasmRpcSetOfModelsIncludingSeedsEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tbd_service_v1_wasm_rpc_test_map_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WasmRpcSetOfModelsIncludingSeeds_WasmRpcSetOfModelsIncludingSeedsEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WasmRpcSetOfModelsIncludingSeeds_WasmRpcSetOfModelsIncludingSeedsEntry) ProtoMessage() {}

func (x *WasmRpcSetOfModelsIncludingSeeds_WasmRpcSetOfModelsIncludingSeedsEntry) ProtoReflect() protoreflect.Message {
	mi := &file_tbd_service_v1_wasm_rpc_test_map_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WasmRpcSetOfModelsIncludingSeeds_WasmRpcSetOfModelsIncludingSeedsEntry.ProtoReflect.Descriptor instead.
func (*WasmRpcSetOfModelsIncludingSeeds_WasmRpcSetOfModelsIncludingSeedsEntry) Descriptor() ([]byte, []int) {
	return file_tbd_service_v1_wasm_rpc_test_map_proto_rawDescGZIP(), []int{1, 0}
}

func (x *WasmRpcSetOfModelsIncludingSeeds_WasmRpcSetOfModelsIncludingSeedsEntry) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *WasmRpcSetOfModelsIncludingSeeds_WasmRpcSetOfModelsIncludingSeedsEntry) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WasmRpcSetOfModelsIncludingSeeds_WasmRpcSetOfModelsIncludingSeedsEntry) GetModelOrSeed() WasmRpcSetOfModelsIncludingSeeds_WasmRpcSetOfModelsIncludingSeedsEntry_WasmRpcSetOfModelsIncludingSeedsEntryType {
	if x != nil {
		return x.ModelOrSeed
	}
	return WasmRpcSetOfModelsIncludingSeeds_WasmRpcSetOfModelsIncludingSeedsEntry_WASM_RPC_SET_OF_MODELS_INCLUDING_SEEDS_ENTRY_TYPE_UNSPECIFIED
}

func (x *WasmRpcSetOfModelsIncludingSeeds_WasmRpcSetOfModelsIncludingSeedsEntry) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

var File_tbd_service_v1_wasm_rpc_test_map_proto protoreflect.FileDescriptor

var file_tbd_service_v1_wasm_rpc_test_map_proto_rawDesc = []byte{
	0x0a, 0x26, 0x74, 0x62, 0x64, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31,
	0x2f, 0x77, 0x61, 0x73, 0x6d, 0x5f, 0x72, 0x70, 0x63, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x6d,
	0x61, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x74, 0x62, 0x64, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x22, 0x8b, 0x01, 0x0a, 0x0e, 0x57, 0x61, 0x73,
	0x6d, 0x52, 0x70, 0x63, 0x54, 0x65, 0x73, 0x74, 0x4d, 0x61, 0x70, 0x12, 0x3f, 0x0a, 0x05, 0x74,
	0x65, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x74, 0x62, 0x64,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x61, 0x73, 0x6d,
	0x52, 0x70, 0x63, 0x54, 0x65, 0x73, 0x74, 0x4d, 0x61, 0x70, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x74, 0x65, 0x73, 0x74, 0x73, 0x1a, 0x38, 0x0a, 0x0a,
	0x54, 0x65, 0x73, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xac, 0x05, 0x0a, 0x20, 0x57, 0x61, 0x73, 0x6d, 0x52,
	0x70, 0x63, 0x53, 0x65, 0x74, 0x4f, 0x66, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x49, 0x6e, 0x63,
	0x6c, 0x75, 0x64, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x65, 0x64, 0x73, 0x12, 0x6e, 0x0a, 0x06, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x56, 0x2e, 0x74, 0x62,
	0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x61, 0x73,
	0x6d, 0x52, 0x70, 0x63, 0x53, 0x65, 0x74, 0x4f, 0x66, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x49,
	0x6e, 0x63, 0x6c, 0x75, 0x64, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x65, 0x64, 0x73, 0x2e, 0x57, 0x61,
	0x73, 0x6d, 0x52, 0x70, 0x63, 0x53, 0x65, 0x74, 0x4f, 0x66, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73,
	0x49, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x65, 0x64, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x1a, 0x97, 0x04, 0x0a, 0x25,
	0x57, 0x61, 0x73, 0x6d, 0x52, 0x70, 0x63, 0x53, 0x65, 0x74, 0x4f, 0x66, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x49, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x65, 0x64, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0xa5, 0x01, 0x0a, 0x0d, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x5f, 0x6f, 0x72, 0x5f, 0x73, 0x65, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x80,
	0x01, 0x2e, 0x74, 0x62, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x57, 0x61, 0x73, 0x6d, 0x52, 0x70, 0x63, 0x53, 0x65, 0x74, 0x4f, 0x66, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x73, 0x49, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x65, 0x64,
	0x73, 0x2e, 0x57, 0x61, 0x73, 0x6d, 0x52, 0x70, 0x63, 0x53, 0x65, 0x74, 0x4f, 0x66, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x49, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x65,
	0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x2e, 0x57, 0x61, 0x73, 0x6d, 0x52, 0x70, 0x63, 0x53,
	0x65, 0x74, 0x4f, 0x66, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x49, 0x6e, 0x63, 0x6c, 0x75, 0x64,
	0x69, 0x6e, 0x67, 0x53, 0x65, 0x65, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x0b, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x4f, 0x72, 0x53, 0x65, 0x65, 0x64, 0x12, 0x1b,
	0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x22, 0xe7, 0x01, 0x0a, 0x29,
	0x57, 0x61, 0x73, 0x6d, 0x52, 0x70, 0x63, 0x53, 0x65, 0x74, 0x4f, 0x66, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x49, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x65, 0x64, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x41, 0x0a, 0x3d, 0x57, 0x41, 0x53,
	0x4d, 0x5f, 0x52, 0x50, 0x43, 0x5f, 0x53, 0x45, 0x54, 0x5f, 0x4f, 0x46, 0x5f, 0x4d, 0x4f, 0x44,
	0x45, 0x4c, 0x53, 0x5f, 0x49, 0x4e, 0x43, 0x4c, 0x55, 0x44, 0x49, 0x4e, 0x47, 0x5f, 0x53, 0x45,
	0x45, 0x44, 0x53, 0x5f, 0x45, 0x4e, 0x54, 0x52, 0x59, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x3b, 0x0a, 0x37,
	0x57, 0x41, 0x53, 0x4d, 0x5f, 0x52, 0x50, 0x43, 0x5f, 0x53, 0x45, 0x54, 0x5f, 0x4f, 0x46, 0x5f,
	0x4d, 0x4f, 0x44, 0x45, 0x4c, 0x53, 0x5f, 0x49, 0x4e, 0x43, 0x4c, 0x55, 0x44, 0x49, 0x4e, 0x47,
	0x5f, 0x53, 0x45, 0x45, 0x44, 0x53, 0x5f, 0x45, 0x4e, 0x54, 0x52, 0x59, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x4d, 0x4f, 0x44, 0x45, 0x4c, 0x10, 0x01, 0x12, 0x3a, 0x0a, 0x36, 0x57, 0x41, 0x53,
	0x4d, 0x5f, 0x52, 0x50, 0x43, 0x5f, 0x53, 0x45, 0x54, 0x5f, 0x4f, 0x46, 0x5f, 0x4d, 0x4f, 0x44,
	0x45, 0x4c, 0x53, 0x5f, 0x49, 0x4e, 0x43, 0x4c, 0x55, 0x44, 0x49, 0x4e, 0x47, 0x5f, 0x53, 0x45,
	0x45, 0x44, 0x53, 0x5f, 0x45, 0x4e, 0x54, 0x52, 0x59, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53,
	0x45, 0x45, 0x44, 0x10, 0x02, 0x42, 0x42, 0x50, 0x01, 0x5a, 0x3e, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x65, 0x6e, 0x66, 0x64, 0x6b, 0x69, 0x6e, 0x67, 0x2f,
	0x74, 0x62, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x65, 0x6e, 0x2f, 0x67, 0x6f,
	0x2f, 0x74, 0x62, 0x64, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x3b,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_tbd_service_v1_wasm_rpc_test_map_proto_rawDescOnce sync.Once
	file_tbd_service_v1_wasm_rpc_test_map_proto_rawDescData = file_tbd_service_v1_wasm_rpc_test_map_proto_rawDesc
)

func file_tbd_service_v1_wasm_rpc_test_map_proto_rawDescGZIP() []byte {
	file_tbd_service_v1_wasm_rpc_test_map_proto_rawDescOnce.Do(func() {
		file_tbd_service_v1_wasm_rpc_test_map_proto_rawDescData = protoimpl.X.CompressGZIP(file_tbd_service_v1_wasm_rpc_test_map_proto_rawDescData)
	})
	return file_tbd_service_v1_wasm_rpc_test_map_proto_rawDescData
}

var file_tbd_service_v1_wasm_rpc_test_map_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tbd_service_v1_wasm_rpc_test_map_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tbd_service_v1_wasm_rpc_test_map_proto_goTypes = []interface{}{
	(WasmRpcSetOfModelsIncludingSeeds_WasmRpcSetOfModelsIncludingSeedsEntry_WasmRpcSetOfModelsIncludingSeedsEntryType)(0), // 0: tbd.service.v1.WasmRpcSetOfModelsIncludingSeeds.WasmRpcSetOfModelsIncludingSeedsEntry.WasmRpcSetOfModelsIncludingSeedsEntryType
	(*WasmRpcTestMap)(nil),                   // 1: tbd.service.v1.WasmRpcTestMap
	(*WasmRpcSetOfModelsIncludingSeeds)(nil), // 2: tbd.service.v1.WasmRpcSetOfModelsIncludingSeeds
	nil,                                      // 3: tbd.service.v1.WasmRpcTestMap.TestsEntry
	(*WasmRpcSetOfModelsIncludingSeeds_WasmRpcSetOfModelsIncludingSeedsEntry)(nil), // 4: tbd.service.v1.WasmRpcSetOfModelsIncludingSeeds.WasmRpcSetOfModelsIncludingSeedsEntry
}
var file_tbd_service_v1_wasm_rpc_test_map_proto_depIdxs = []int32{
	3, // 0: tbd.service.v1.WasmRpcTestMap.tests:type_name -> tbd.service.v1.WasmRpcTestMap.TestsEntry
	4, // 1: tbd.service.v1.WasmRpcSetOfModelsIncludingSeeds.models:type_name -> tbd.service.v1.WasmRpcSetOfModelsIncludingSeeds.WasmRpcSetOfModelsIncludingSeedsEntry
	0, // 2: tbd.service.v1.WasmRpcSetOfModelsIncludingSeeds.WasmRpcSetOfModelsIncludingSeedsEntry.model_or_seed:type_name -> tbd.service.v1.WasmRpcSetOfModelsIncludingSeeds.WasmRpcSetOfModelsIncludingSeedsEntry.WasmRpcSetOfModelsIncludingSeedsEntryType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_tbd_service_v1_wasm_rpc_test_map_proto_init() }
func file_tbd_service_v1_wasm_rpc_test_map_proto_init() {
	if File_tbd_service_v1_wasm_rpc_test_map_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tbd_service_v1_wasm_rpc_test_map_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WasmRpcTestMap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tbd_service_v1_wasm_rpc_test_map_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WasmRpcSetOfModelsIncludingSeeds); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tbd_service_v1_wasm_rpc_test_map_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WasmRpcSetOfModelsIncludingSeeds_WasmRpcSetOfModelsIncludingSeedsEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tbd_service_v1_wasm_rpc_test_map_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tbd_service_v1_wasm_rpc_test_map_proto_goTypes,
		DependencyIndexes: file_tbd_service_v1_wasm_rpc_test_map_proto_depIdxs,
		EnumInfos:         file_tbd_service_v1_wasm_rpc_test_map_proto_enumTypes,
		MessageInfos:      file_tbd_service_v1_wasm_rpc_test_map_proto_msgTypes,
	}.Build()
	File_tbd_service_v1_wasm_rpc_test_map_proto = out.File
	file_tbd_service_v1_wasm_rpc_test_map_proto_rawDesc = nil
	file_tbd_service_v1_wasm_rpc_test_map_proto_goTypes = nil
	file_tbd_service_v1_wasm_rpc_test_map_proto_depIdxs = nil
}
